### PR TITLE
Extract variables and outputs to the separate files

### PR DESCRIPTION
**Pull request by bronislav**

### CODE REVIEW

**Comment by antonbabenko** [comment]
Thanks Anton :)

The reason I was following in this PR is that if there is just one resource defined in it I put variables and output into the same file. I did the same in other modules, for eg, https://github.com/terraform-community-modules/tf_aws_vpc_only

If there would be 2+ resources defined in this module, then your PR is good. Or do you have any specific reason for separation of code ?

**Comment by bronislav** [comment]
I'm working on additional pull request, which add option to create nat instances instead of nat gateways.

**Comment by antonbabenko** [comment]
Great. Let's make a separate module instead of committing to this module.

**Comment by bronislav** [comment]
Is there a reason why you suggest to put such changes in the separate module?

I mean it's fairly easy to imaging use case when such resources could be required in same subnets. (Redirect all traffic through nat getaways and use nat instances to access resources in private subnets).

Does it make sense? Or there are other best practices for such use case?

**Comment by antonbabenko** [comment]
This module takes care of `aws_nat_gateway` in its core, not NAT instances.

There is already another module ( https://github.com/terraform-community-modules/tf_aws_nat ), which may be used or customized if you need to have NAT instances in addition of NAT gateway.

I don't think it is a good idea of mixing both into one module (this or another).

**Comment by bronislav** [comment]
I see. Thank you for the explanation.

**Pull request closed without merging**
